package com.tunisales.business.service.mapper;

import com.tunisales.business.domain.SalesReturn;
import com.tunisales.business.domain.SalesReturnLine;
import com.tunisales.business.service.dto.SalesReturnDTO;
import com.tunisales.business.service.dto.SalesReturnLineDTO;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Sub-step 2.5 — manual mapper for the {@link SalesReturn}/{@link SalesReturnLine} pair.
 *
 * <p>The mapping is intentionally not generated by MapStruct: the bidirectional
 * association makes the generated code awkward to read, and a hand-written
 * mapper is straightforward enough.</p>
 */
@Component
public class SalesReturnMapper {

    public SalesReturnDTO toDto(SalesReturn entity) {
        if (entity == null) return null;
        SalesReturnDTO dto = new SalesReturnDTO();
        dto.setId(entity.getId());
        dto.setTenantId(entity.getTenantId());
        dto.setInvoiceId(entity.getInvoiceId());
        dto.setReturnNumber(entity.getReturnNumber());
        dto.setReason(entity.getReason());
        dto.setStatus(entity.getStatus());
        dto.setRefundAmount(entity.getRefundAmount());
        dto.setCreatedByLogin(entity.getCreatedByLogin());
        dto.setCreatedAt(entity.getCreatedAt());
        dto.setProcessedAt(entity.getProcessedAt());
        Set<SalesReturnLineDTO> lines = new HashSet<>();
        if (entity.getLines() != null) {
            for (SalesReturnLine l : entity.getLines()) {
                SalesReturnLineDTO ld = new SalesReturnLineDTO();
                ld.setId(l.getId());
                ld.setInvoiceLineId(l.getInvoiceLineId());
                ld.setImei(l.getImei());
                ld.setStockItemId(l.getStockItemId());
                ld.setCondition(l.getCondition());
                ld.setRefundAmount(l.getRefundAmount());
                lines.add(ld);
            }
        }
        dto.setLines(lines);
        return dto;
    }

    public List<SalesReturnDTO> toDto(List<SalesReturn> entities) {
        List<SalesReturnDTO> out = new ArrayList<>();
        if (entities != null) {
            for (SalesReturn e : entities) out.add(toDto(e));
        }
        return out;
    }

    public SalesReturn toEntity(SalesReturnDTO dto) {
        if (dto == null) return null;
        SalesReturn entity = new SalesReturn();
        entity.setId(dto.getId());
        entity.setTenantId(dto.getTenantId());
        entity.setInvoiceId(dto.getInvoiceId());
        entity.setReturnNumber(dto.getReturnNumber());
        entity.setReason(dto.getReason());
        entity.setStatus(dto.getStatus());
        entity.setRefundAmount(dto.getRefundAmount());
        entity.setCreatedByLogin(dto.getCreatedByLogin());
        entity.setCreatedAt(dto.getCreatedAt());
        entity.setProcessedAt(dto.getProcessedAt());
        return entity;
    }
}
